name: Validate

on:
  pull_request:
    paths:
      - 'data/**'
  push:
    paths:
      - 'data/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Validate JSON Files
        id: json-validation
        run: |
          cd data
          for file in *.json; do
            if ! jq . "$file" >/dev/null 2>&1; then
              echo "Invalid JSON in $file"
              exit 1
            fi
          done

      - name: Check info.js Modification
        id: infojs-modified
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q "data/info.js"; then
            echo "✅ ./data/info.js has been modified"
          else
            echo "❌ ./data/info.js was not modified"
            echo "After adding a new spinner, you need to increment the variable totalSpinners by 1 located in the file data/info.js"
            exit 1
          fi
